export const FETCH_MEMES = "FETCH_MEMES";
export const SHOW_SPINNER = "SHOW_SPINNER";
export const CLOSE_SPINNER = "CLOSE_SPINNER";
export const PICK_MEME = "PICK_MEME";
export const CREATE_MEME = "CREATE_MEME";
export const SHOW_BACKDROP = "SHOW_BACKDROP";
export const CLOSE_BACKDROP = "CLOSE_BACKDROP";
export const TOGGLE_READY_MEME = "TOGGLE_READY_MEME";
